import { UserReview } from "@/types/reviews";

export const userReviews: UserReview[] = [
    {
        id: 1,
        firstName: "Ali",
        lastName: "Khan",
        rating: 5,
        reviewText: "I started noticing less hair fall within a couple of weeks. It actually fits easily into my daily routine.",
        date: "2026-03-12",
    },
    {
        id: 2,
        firstName: "Sara",
        lastName: "Ahmed",
        rating: 4,
        reviewText: "The formula feels light and natural. Results took a bit of time, but I can see improvement now.",
        date: "2026-02-28",
    },
    {
        id: 3,
        firstName: "Daniel",
        lastName: "Kim",
        rating: 4,
        reviewText: "Clean formula and easy to apply. I like that it doesn't leave any residue.",
        date: "2026-01-30",
    },
    {
        id: 4,
        firstName: "Usman",
        lastName: "Raza",
        rating: 5,
        reviewText: "I was skeptical at first, but my thinning areas look noticeably better. Definitely worth trying.",
        date: "2026-03-05",
    },
    {
        id: 5,
        firstName: "Emily",
        lastName: "Carter",
        rating: 5,
        reviewText: "Honestly surprised by how quickly I saw results. My hair feels fuller and healthier.",
        date: "2026-03-18",
    },
    {
        id: 6,
        firstName: "Bilal",
        lastName: "Sheikh",
        rating: 5,
        reviewText: "Simple application and real results. My confidence has improved a lot.",
        date: "2026-03-21",
    },
    {
        id: 7,
        firstName: "Lucas",
        lastName: "Martinez",
        rating: 4,
        reviewText: "Good product overall. Took about a month to notice visible changes, but it's working.",
        date: "2026-02-14",
    },
    {
        id: 8,
        firstName: "Sophie",
        lastName: "Dubois",
        rating: 5,
        reviewText: "Très impressed with the quality. It feels gentle but effective.",
        date: "2026-03-02",
    },
    {
        id: 9,
        firstName: "Isabella",
        lastName: "Rossi",
        rating: 5,
        reviewText: "One of the best additions to my hair care routine. Results are consistent.",
        date: "2026-03-25",
    },
    {
        id: 10,
        firstName: "Noah",
        lastName: "Anderson",
        rating: 3,
        reviewText: "It's decent, but I expected faster results. Still testing it long-term.",
        date: "2026-02-09",
    },
    {
        id: 11,
        firstName: "Hina",
        lastName: "Malik",
        rating: 4,
        reviewText: "No harsh smell, no irritation. That alone makes it better than most products I've used.",
        date: "2026-01-19",
    },
    {
        id: 12,
        firstName: "Yuki",
        lastName: "Tanaka",
        rating: 5,
        reviewText: "Lightweight, effective, and very easy to use. I'm really happy with the results.",
        date: "2026-03-29",
    }
];